image:
  repository: ghcr.io/dani-garcia/vaultwarden
  tag: "1.32.7"

persistence:
  enabled: true
  size: 10Gi
  storageClassName: local-path

ingress:
  enabled: true
  className: "nginx"  # O "caddy"
  hosts:
    - host: vault.petruz-central.it  # ← CAMBIA
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: vault-tls

env:
  TZ: "Europe/Rome"
  WEBSOCKET_ENABLED: "true"
  SIGNUPS_ALLOWED: "false"
  ADMIN_TOKEN: "openssl-rand-base64-48-change-this!!!"  # ← SUPER IMPORTANTE CAMBIA
  DOMAIN: "https://vault.petruz-central.it" 

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
